definitions:
  controllers.Resposta:
    properties:
      mensagem:
        type: string
    type: object
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  models.Aluno:
    properties:
      cpf:
        type: string
      createdAt:
        type: string
      deletedAt:
        $ref: '#/definitions/gorm.DeletedAt'
      id:
        type: integer
      nome:
        type: string
      rg:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
paths:
  /alunos:
    get:
      consumes:
      - application/json
      description: Retorna uma lista de todos os alunos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Aluno'
            type: array
      summary: Retorna todos os alunos
      tags:
      - Alunos
    post:
      consumes:
      - application/json
      description: Adiciona um novo aluno ao banco de dados
      parameters:
      - description: Aluno
        in: body
        name: aluno
        required: true
        schema:
          $ref: '#/definitions/models.Aluno'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Aluno'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.Resposta'
      summary: Cadastra um novo aluno
      tags:
      - Alunos
  /alunos/{id}:
    delete:
      consumes:
      - application/json
      description: Remove um aluno do banco de dados pelo ID
      parameters:
      - description: Aluno ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.Resposta'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.Resposta'
      summary: Deleta um aluno pelo ID
      tags:
      - Alunos
    get:
      consumes:
      - application/json
      description: Retorna os dados de um aluno específico pelo ID
      parameters:
      - description: Aluno ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Aluno'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.Resposta'
      summary: Retorna um aluno pelo ID
      tags:
      - Alunos
    patch:
      consumes:
      - application/json
      description: Atualiza os dados de um aluno específico pelo ID
      parameters:
      - description: Aluno ID
        in: path
        name: id
        required: true
        type: integer
      - description: Aluno
        in: body
        name: aluno
        required: true
        schema:
          $ref: '#/definitions/models.Aluno'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Aluno'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controllers.Resposta'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.Resposta'
      summary: Edita um aluno pelo ID
      tags:
      - Alunos
  /alunos/cpf/{cpf}:
    get:
      consumes:
      - application/json
      description: Retorna os dados de um aluno específico pelo CPF
      parameters:
      - description: Aluno CPF
        in: path
        name: cpf
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Aluno'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/controllers.Resposta'
      summary: Retorna um aluno pelo CPF
      tags:
      - Alunos
swagger: "2.0"
